const OS = {
  start: "maitriser-linux",
  nodes: [
    { id: "maitriser-linux", title: "Maîtriser Linux", type: "etape",
      description: "GNU/Linux est un système d'exploitation libre et opensource. Comme le code source est ouvert, il est particulièrement adapté pour toute personne souhaitant étudier le fonctionnement de son ordinateur." },
    { id: "linux-install", title: "Installer un environnement Linux", type: "etape", level: 1,
      description: "Installer un environnement Linux sur sa machine est le premier pas vers la libération !",
      resources: [{ label: "WSL", url: "https://learn.microsoft.com/fr-fr/windows/wsl/install", note: "installer un environnement Linux en ligne de commande sous Windows" }, { label: "Initiez-vous à Linux", url: "https://openclassrooms.com/fr/courses/7170491-initiez-vous-a-linux", note: "installer et configurer une distribution Linux sur votre ordinateur" }] },
    { id: "ligne-commande", title: "Apprendre à utiliser la ligne de commande", type: "etape", level: 2,
      description: "La ligne de commande est un outil fondamental pour contrôler son système d'exploitation.",
      resources: [{ label: "Terminus", url: "https://luffah.xyz/bidules/Terminus/", note: "Un jeu en ligne pour apprendre la ligne de commande." }, { label: "GameShell", url: "https://github.com/phyver/GameShell", note: "Un jeu sous Linux pour apprendre la ligne de commande." }, { label: "pwn.college : linux", url: "https://pwn.college/linux-luminarium/", note: "Apprendre pas à pas à utiliser linux" }] },
    { id: "scripts-systeme", title: "Écrire des scripts système", type: "etape", level: 3,
      description: "Il est possible d'écrire des programmes à l'aide des commandes linux : on parle de scripts bash. L'exécution des scripts peuvent être automatisés avec l'outil cron.",
      resources: [{ label: "Shell Scripting Tutorial", url: "https://www.shellscript.sh/" }, { label: "cron", url: "https://doc.ubuntu-fr.org/cron" }] },
    { id: "editeur-code", title: "Apprendre un éditeur de code", type: "etape",
      description: "Un.e développeur.euse passe la plupart de son temps à écrire du texte. Pour cette raison, il est important d'avoir un éditeur confortable." },
    { id: "vscode", title: "VScode", type: "etape", level: 1,
      description: "Un éditeur de code facile à prendre en main, avec beaucoup de fonctionnalités.",
      resources: [{ label: "VScode", url: "https://code.visualstudio.com/" }] },
    { id: "vim", title: "ViM", type: "etape", level: 2,
      description: "ViM est un éditeur de texte icônique dont la prise en main peut s'avérer... surprenante. Difficile de s'en passer une fois habitué. Un éditeur de vrai geek.",
      resources: [{ label: "vimtutor", url: "https://vimschool.netlify.app/introduction/vimtutor/", note: "Un tutoriel rapide pour apprendre les commandes ViM." }, { label: "ViM adventures", url: "https://vim-adventures.com/", note: "Apprendre les commandes ViM sous forme de jeu." }, { label: "ViM Hero", url: "https://www.vim-hero.com/", note: "Un tutoriel en ligne pour apprendre les commandes ViM." }, { label: "vimtutor-sequel", url: "https://github.com/micahkepe/vimtutor-sequel", note: "La suite de vimtutor. Tutoriel sur des notions avancées." }] },
    { id: "emacs", title: "Emacs", type: "etape", level: 3,
      description: "Un autre éditeur de vrai geek. Des possibilités de configurations incroyable, mais demande beaucoup de connaissances.",
      resources: [{ label: "Emacs Tour", url: "https://www.gnu.org/software/emacs/tour/" }] },
    { id: "prog-editeur", title: "Programmer son éditeur", type: "etape", level: 4,
      description: "Il est toujours possible de configurer son éditeur de texte préféré pour lui ajouter de nouvelles fonctionnalités. Attention, pour les experts !",
      resources: [{ label: "protesilaos's config", url: "https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/" }, { label: "emacs-bedrock", url: "https://codeberg.org/ashton314/emacs-bedrock" }] },
    { id: "prog-systeme", title: "Programmation système", type: "etape" },
    { id: "construire-ordi", title: "Construire un ordinateur", type: "etape", level: 3,
      description: "Un ordinateur ne comprend que des 0 et des 1. Oui mais c'est à dire ?",
      resources: [{ label: "Turing Complete", url: "https://store.steampowered.com/app/1444480/Turing_Complete/", note: "Un jeu sur steam où vous construisez un ordinateur \"à partir de rien\"." }, { label: "NAND Game", url: "https://nandgame.com/", note: "Une version en ligne et plus courte du jeu Turing Complete" }, { label: "Building a computer with LogiSim", url: "https://www.youtube.com/playlist?list=PLUOaI24LpvQN2Y53vWepO2LMabKPIplar", note: "Un cours Youtube sur la construction d'un ordinateur." }] },
    { id: "bas-niveau", title: "Programmation bas niveau", type: "etape",
      resources: [{ label: "pwn.college : computing 101", url: "https://pwn.college/computing-101/" }] },
    { id: "assembleur", title: "Langage assembleur", type: "etape", level: 4,
      description: "Le langage assembleur est ce qui se rapproche le plus de la manière dont les instructions sont exécutées sur le CPU.",
      resources: [{ label: "Apprendre l'assembleur", url: "https://coddy.tech/landing/fr/assembly", note: "Des leçons interactives sur coddy.tech" }, { label: "(pwn.college) Assembly Crash Course", url: "https://pwn.college/cse365-s2024/assembly-crash-course/", note: "Comprendre les bases de l'assembleur." }, { label: "Assembly Language Programming", url: "https://metalup.org/al/AL_Student.pdf", note: "Un manuel de cours" }, { label: "Assembly Language Simulator", url: "https://www.peterhigginson.co.uk/AQA/", note: "Exécuter des programmes assembleur étape par étape en ligne" }] },
    { id: "langage-c", title: "Langage C", type: "etape", level: 4,
      description: "À peine plus haut niveau que l'assembleur.",
      resources: [{ label: "(pwn.college) Intro to Programming Languages", url: "https://pwn.college/intro-to-programming-languages/" }, { label: "Learn C", url: "https://www.codecademy.com/learn/paths/c" }] },
    { id: "gerer-un-serveur-web", title: "Gérer un serveur web", type: "etape" },
    { id: "page-locale", title: "Créer une page web locale", type: "etape", level: 1,
      description: "Créer une page HTML, dont le style est géré par un fichier CSS et l'interactivité par un programme javascript.",
      resources: [{ label: "Créer votre site web avec HTML et CSS", url: "https://openclassrooms.com/en/courses/1603881-creez-votre-site-web-avec-html5-et-css3" }, { label: "Apprendre le CSS en jouant", url: "https://dev.to/douiri/learn-css-with-these-games-5e4m" }] },
    { id: "reseau-lycee", title: "Explorer le réseau du lycée", type: "etape", level: 2,
      description: "Comprendre la notion de réseau de machines. Se connecter à une machine en SSH. Interagir avec une machine distante." },
    { id: "projets-web", title: "Réaliser des projets", type: "etape" },
    { id: "creer-systeme-de-chat", title: "Créer système de chat", type: "etape", level: 2,
      description: "Pour pouvoir vous parler en cours en toute discrétion." },
    { id: "creer-serveur-de-fichiers", title: "Créer serveur de fichiers", type: "etape", level: 2,
      description: "Pour pouvoir accès à vos fichiers quelque soit votre ordinateur." },
    { id: "creer-serveur-mail", title: "Créer serveur mail", type: "etape", level: 2,
      description: "Pour que l'on puisse vous envoyer des mails sur votre propre machine." },
    { id: "utiliser-raspberry-pi-comme-serveur", title: "Utiliser raspberry pi comme serveur", type: "etape", level: 3,
      description: "Pour avoir un serveur web à soi." },
  ],
  edges: [
    { from: "maitriser-linux", to: "linux-install" }, { from: "linux-install", to: "ligne-commande" }, { from: "ligne-commande", to: "scripts-systeme" },
    { from: "editeur-code", to: "vscode" }, { from: "editeur-code", to: "vim" }, { from: "vim", to: "emacs" },
    { from: "emacs", to: "prog-editeur" }, { from: "vscode", to: "prog-editeur" }, { from: "prog-systeme", to: "construire-ordi" },
    { from: "prog-systeme", to: "bas-niveau" }, { from: "bas-niveau", to: "assembleur" }, { from: "bas-niveau", to: "langage-c" },
    { from: "ligne-commande", to: "gerer-un-serveur-web" }, { from: "gerer-un-serveur-web", to: "page-locale" }, { from: "gerer-un-serveur-web", to: "reseau-lycee" },
    { from: "page-locale", to: "projets-web" }, { from: "reseau-lycee", to: "projets-web" }, { from: "projets-web", to: "creer-systeme-de-chat" },
    { from: "projets-web", to: "creer-serveur-de-fichiers" }, { from: "projets-web", to: "creer-serveur-mail" }, { from: "projets-web", to: "utiliser-raspberry-pi-comme-serveur" },
  ]
};