const PROGRAMMATION = {
  start: "decouvrir-la-pensee-informatique",
  nodes: [
    { id: "decouvrir-la-pensee-informatique", title: "Découvrir la pensée informatique", type: "etape",
      description: "Comprendre comment on raisonne en informatique : décomposer un problème et écrire une suite d'instructions." },
    { id: "concours-castor", title: "Concours Castor", type: "etape", level: 1,
      description: "Un concours en ligne de logique et de réflexion, où on résout des problèmes informatiques sans rien programmer. À destination des collégien.ne.s et lycée.ne.s. Vous pouvez vous entraîner sur les archives des éditions précédentes. https://concours.castor-informatique.fr/" },
    { id: "apprendre-les-bases-de-python", title: "Apprendre les bases de Python", type: "etape", level: 1,
      description: "Variables, conditions, boucles, fonctions et listes : les notions de base de tout programme. Apprendre Python pour découvrir et maîtriser ces notions.",
      resources: [{ label: "France IOI", url: "https://www.france-ioi.org/algo/chapters.php", note: "Apprendre la programmation étape par étape, au travers de défis et de jeux en ligne." }, { label: "Future Coder", url: "https://fr.futurecoder.io/", note: "Un cours de programmation en ligne et interactif." }, { label: "CodEx", url: "https://codex.forge.apps.education.fr/", note: "Site d'exercices pour s'entraîner sur les notions du cours de première et terminale NSI." }, { label: "Python Full Course (free)", url: "https://www.youtube.com/watch?v=XKHEtdqhLK8", note: "Cours complet de programmation Python sur Youtube." }, { label: "LeetCode", url: "https://leetcode.com/", note: "Des challenges de programmation avancée, dans différents langages." }, { label: "Advent Of Code", url: "https://adventofcode.com/", note: "Un calendrier de l'avent. Chaque jour un nouveau challenge de programmation." }] },
    { id: "projets-web", title: "Réaliser des projets", type: "objectif",
      description: "Apprendre à programmer passe d'abord par la réalisation de projet. Ils peuvent prendre la forme de jeux, de compétition de programmation, ou de création d'applications spécifiques." },
    { id: "jeux-avec-python", title: "Jeux avec Python", type: "etape",
      description: "On peut créer des jeux directement avec Python, en utilisant des librairies." },
    { id: "librairie-pyxel", title: "Librairie Pyxel", type: "etape", level: 2,
      description: "Une librairie 2D basique qui permet de créer des jeux rétros en pixel art.",
      resources: [{ label: "TP - Découvrir Pyxel", url: "https://forge.apps.education.fr/florian.picard/nsi-premiere/-/raw/master/0%20-%20La%20Nuit%20du%20Code/Formation%20%C3%A0%20pyxel/1%20-%20Pyxel,%20qu'est-ce%20que%20c'est/tp1_introduction.pdf?ref_type=heads&inline=false" }, { label: "TP - Éditeur de ressources", url: "https://forge.apps.education.fr/florian.picard/nsi-premiere/-/raw/master/0%20-%20La%20Nuit%20du%20Code/Formation%20%C3%A0%20pyxel/2%20-%20Pyxel%20Editor/tp2_pyxeledit.pdf?ref_type=heads&inline=false" }, { label: "TP - Interactivité", url: "https://forge.apps.education.fr/florian.picard/nsi-premiere/-/raw/master/0%20-%20La%20Nuit%20du%20Code/Formation%20%C3%A0%20pyxel/3%20-%20Animations/tp3_interactivite.pdf?ref_type=heads&inline=false" }, { label: "Tutoriel Pyxel Première", url: "https://www.cahiernum.net/J682W5" }, { label: "Tutoriel Pyxel Terminale", url: "https://www.cahiernum.net/KV8H5B" }] },
    { id: "librairie-pygame", title: "Librairie Pygame", type: "etape", level: 3,
      description: "La librairie de référence pour les jeux 2D en Python, plus complète mais plus difficile d'accès.",
      resources: [{ label: "Newbie Guide", url: "https://www.pygame.org/docs/tut/newbieguide.html", note: "Quelques conseils pour débuter la programmation avec pygame." }] },
    { id: "competitions-de-programmation", title: "Compétitions de programmation", type: "etape",
      description: "Participer à des compétitions de programmation est un excellent moyen de progresser. Toutes les compétitions se font en équipe !" },
    { id: "concours-algorea", title: "Concours Algoréa", type: "etape", level: 2,
      description: "Un concours d'algorithmique et de programmation en ligne, ouvert aux collégien.ne.s et aux lycéen.ne.s." },
    { id: "la-nuit-du-code", title: "La Nuit du Code", type: "etape", level: 3,
      description: "Un concours de création de jeu vidéo en équipe, en une nuit. Le jeu doit être écrit en Python, en utilisant la librairie pyxel.",
      resources: [{ label: "Site officiel de la Nuit du Code", url: "https://www.nuitducode.net/" }, { label: "Sélection internationale de jeux", url: "https://www.nuitducode.net/jeux-ndc", note: "Les jeux gagnants des différentes éditions de la Nuit du Code." }] },
    { id: "jeux-sans-python", title: "Jeux sans Python", type: "etape",
      description: "Les professionnels n'utilisent pas Python pour créer des jeux : ils crééent des jeux avec un moteur de jeu. Attention ces outils nécessitent l'apprentissage d'un autre langage de programmation !",
      resources: [{ label: "(Youtube) Génération procédurale sur une grille", url: "https://www.youtube.com/watch?v=Y19Mw5YsgjI" }] },
    { id: "godot", title: "Godot", type: "etape", level: 3,
      description: "Un moteur de jeu libre et gratuit, pour la 2D comme pour la 3D.",
      resources: [{ label: "2D game", url: "https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html", note: "Tutoriel pour créer un jeu en 2D." }, { label: "3D game", url: "https://docs.godotengine.org/en/stable/getting_started/first_3d_game/index.html", note: "Tutoriel pour créer un jeu en 3D." }, { label: "Godot2D", url: "https://devga.me/tutorials/godot2d/", note: "Tutoriel pour créer un jeu 2D à partir de zéro." }, { label: "Big List of Great Tutorial", url: "https://godotforums.org/d/40607-a-big-list-of-great-free-godot-tutorial-series-videos", note: "Beaucoup de tutoriels pour Godot en 2D, en 3D." }] },
    { id: "unity", title: "Unity", type: "etape", level: 4,
      description: "Un moteur de jeu professionnel très répandu, pour la 2D, la 3D et le mobile." },
    { id: "programmation-avancee", title: "Programmation avancée", type: "etape",
      resources: [{ label: "LeetCode", url: "https://leetcode.com/", note: "des challenges de programmation avancée, dans différents langages." }] },
    { id: "sql", title: "SQL", type: "etape", level: 1,
      description: "Les bases de données sont essentielles en informatique pour stocker de larges quantités d'informations. SQL est un langage utilisé pour interroger des bases de données.",
      resources: [{ label: "Exercices SQL", url: "https://nreveret.forge.apps.education.fr/exercices_bdd/", note: "Des exercices de niveau terminale NSI en SQL." }, { label: "SQL Island", url: "http://wwwlgis.informatik.uni-kl.de/extra/game/?lang=en", note: "Découvrir la syntaxe SQL au travers d'un tutoriel en ligne sous forme de jeu." }, { label: "SQL Zoo", url: "https://sqlzoo.net/wiki/SQL_Tutorial" }, { label: "SQL Murder Mystery", url: "https://mystery.knightlab.com/", note: "Un jeu d'enquête dans lequel il est nécessaire de connaître la syntaxe SQL pour trouver le coupable." }] },
    { id: "programmation-orientee-objet", title: "Programmation Orientée Objet", type: "etape", level: 3,
      description: "Organiser un programme en objets qui regroupent des données et des actions." },
    { id: "recursivite", title: "Récursivité", type: "etape", level: 4,
      description: "Pour comprendre à quoi sert la récursivité, il faut d'abord comprendre à quoi sert la récursivité." },
  ],
  edges: [
    { from: "decouvrir-la-pensee-informatique", to: "concours-castor" }, { from: "decouvrir-la-pensee-informatique", to: "apprendre-les-bases-de-python" }, { from: "apprendre-les-bases-de-python", to: "projets-web" },
    { from: "projets-web", to: "jeux-avec-python" }, { from: "jeux-avec-python", to: "librairie-pyxel" }, { from: "librairie-pyxel", to: "librairie-pygame" },
    { from: "projets-web", to: "competitions-de-programmation" }, { from: "competitions-de-programmation", to: "concours-algorea" }, { from: "competitions-de-programmation", to: "la-nuit-du-code" },
    { from: "librairie-pyxel", to: "la-nuit-du-code" }, { from: "projets-web", to: "jeux-sans-python" }, { from: "jeux-sans-python", to: "godot" },
    { from: "jeux-sans-python", to: "unity" }, { from: "apprendre-les-bases-de-python", to: "programmation-avancee" }, { from: "programmation-avancee", to: "sql" },
    { from: "programmation-avancee", to: "programmation-orientee-objet" }, { from: "programmation-avancee", to: "recursivite" },
  ]
};